### ISSUE TITLE
Unable to adjust paper size on "New PDF Contact Sheet"

### ISSUE THREAD

**Issue by rcolsm** [bborn/Curbly-DIY-Photobooth#1]
I was surprised that you keep update the software, I really like it. Unfortunately I'm having an issue while printing by using 80mm wide thermal printer. So when I print to A4/letter size, the result will be like this one. Any solution or suggestion?

Thanks in advance!

![imaasdge](https://cloud.githubusercontent.com/assets/14244755/13083925/af8c2d62-d509-11e5-80c7-a1cd0b4b5aa7.jpg)

I've found a similar issue that the user unable to adjust paper size (not solved): http://apple.stackexchange.com/questions/224288/how-can-i-add-additional-paper-sizes-to-automator-services

**Comment by bborn** [comment]
Sorry - I don't see any way to add additional sizes to the `New PDF Contact Sheet` action.

**Comment by rcolsm** [comment]
I've found the solution, using `New PDF from Images` will solve the issue; instead by using `New PDF Contact Sheet` action.

**Comment by bborn** [comment]
Nice. Feel free to fork and submit a pull request.
